id: IB756C24F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:13:50+00:00'
last_modified: '2022-06-08T09:18:10.230045+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14742
  title: མཁའ་འགྲོ་མ་འགྲོ་བ་བཟང་མོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4D7C:
      image_group_id: I2PD19553
      title: ''
      total_pages: 152
      order: 1
      base_file: 4D7C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
